Fix regression on the plotting API when verbose is False (#161)
Fix the following regression from
https://github.com/pyspark-ai/pyspark-ai/pull/159:
```
>>> df.ai.plot("Bar plot of the top 5 most populous cities")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xinrong.meng/pyspark-ai/pyspark_ai/ai_utils.py", line 66, in plot
    return self.spark_ai.plot_df(self.df_instance, desc, cache)
  File "/Users/xinrong.meng/pyspark-ai/pyspark_ai/pyspark_ai.py", line 525, in plot_df
    plot_chain = PythonExecutor(
  File "/opt/miniconda3/envs/eng_dev/lib/python3.9/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PythonExecutor
logger
  none is not an allowed value (type=type_error.none.not_allowed)
```

Also, this PR fixes the file location in the end_to_end test case